### ISSUE TITLE
A simple question

### ISSUE THREAD

**Issue by crazylinuxsir** [google/android-classyshark#1]
after I read Get Started.md   

I don't know what's different between android-classyshark  and JD-GUI

android-classyshark can work when my app run  and see what's class i use in jar at the moment ?

**Comment by borisf** [comment]
@crazylinuxsir the key difference is the problem each of these tools is solving:
JD-GUI - decompiler, i.e. translates Java executables to Java sources
ClassyShark - executables browser, i.e. shows the structural info (using reflection) in a fast way. In other words ClassyShark shows you what your runtime environment sees (again using reflection), with incremental/fuzzy/camel search features.  All in all ClassyShark doesn't decompile anything.
