### ISSUE TITLE
ClassyShark does not terminate when ran with command line arguments

### ISSUE THREAD

**Issue by agatti** [google/android-classyshark#105]
On OSX 10.11, and Java 1.8.0_77, launching ClassyShark 6.4 with any command line arguments will not let it terminate and return back to the shell (bash or zsh does not matter).  Here's an animated gif showing the issue:

![cs](https://cloud.githubusercontent.com/assets/235740/15712970/0dad5b92-2847-11e6-8374-4ffea4cf0bc4.gif)

Cheers!

**Comment by andreban** [comment]
I was able to reproduce the error on 6.4. It seems to be fixed since version 6.5.
