### ISSUE TITLE
Unable to detect instrumented code in apk files.

### ISSUE THREAD

**Issue by Tao93** [google/android-classyshark#122]
I instrumented some code into onCreate method of MainActivity with [Transform API](http://tools.android.com/tech-docs/new-build-system/transform-api) and [ASM](http://asm.ow2.org) . The apk I got ran as I expected, and I could see the instrumented code in the apk with jar2dex and JD-gui. However, the ClassyShark was unable to detect the instrumented code. Any reply or explanation is appreciated. Thanks!

**Comment by borisf** [comment]
Could you please attached a sample project so we can re-create & analyse the bug from our end. Thanks.

**Comment by Tao93** [comment]
I am really sorry but I thought that ClassyShark decompiles each class in an apk and displays them, which seemed something more powerful than JD-GUI, and didn't realised that after so many glances. Thank you for your reply. Please feel free to close this issue. BTW, get and display concrete decompiled code seems an attractive feature. Thank you!
