### ISSUE TITLE
Instructions to build ClassySharkWS?

### ISSUE THREAD

**Issue by CaledoniaProject** [google/android-classyshark#124]
Can you add instructions to build ClassySharkWS?

**Comment by borisf** [comment]
If you use an IntelliJ, then use "File --> New --> Project from existing sources" flow. Put ClassySharkWS as the root folder.

Else, use [Retrobuid](https://github.com/borisf/RetroBuild)

If there anything else I am missing ?

**Comment by borisf** [comment]
And yes, I will add a section to readme

**Comment by CaledoniaProject** [comment]
Oh, I meant like a command line compilation guide

**Comment by CaledoniaProject** [comment]
I'll try the IntelliJ solution as well

**Comment by borisf** [comment]
Command line, either use RetroBuild, or you are welcome to submit a pull request, with your favorite tool chain ;)
