### ISSUE TITLE
UI and --methodcount flag report different numbers

### ISSUE THREAD

**Issue by marwanad** [google/android-classyshark#130]
The numbers of method in the UI component and those reported using `-methodcounts` flag report different numbers.
Is this expected? Does the `-methodcounts` not report the dex method count?

**Comment by borisf** [comment]
UI - classes view shows both referenced and defined methods (reads classes.dex header)
UI - packages shows only referenced methods

-methodcounts should show the same data as UI - packages, if it is not the case this is a bug //cc @andreban

**Comment by marwanad** [comment]
It does show the same count as UI -packages. That makes more sense now.
I thought `-methodcounts` would show the dex counts.
Thanks.
