### ISSUE TITLE
Export packages used within the APK

### ISSUE THREAD

**Issue by paul-matthews** [google/android-classyshark#140]
List packages used within an APK with a view to offering a tool to extract common libraries used across multiple APKs.

A proposed method signature could be:
`java -jar ClassyShark.jar -exportpackages app-debug.apk`

Which outputs a file with the following format:
```
android.support.v7.util
android.support.v7.widget
```

With the logical next step to be:
`java -jar ClassyShark.jar -exportcommonpackages app-debug.apk app-production.apk app-feature.apk`

With the format including the count:
```
android.support.v7.util - 3
android.support.v7.widget - 2
```

**Comment by borisf** [comment]
Done, here is how to do it https://github.com/borisf/classyshark-packages-exporter/blob/master/src/ClassySharkPackagesExporter.java
