### ISSUE TITLE
Export individual files

### ISSUE THREAD

**Issue by dandv** [google/android-classyshark#152]
I'm trying to extract the manifest from an APK. I imagine that after I open the APK, I could click on `AndroidManifest.xml` and then on the Export toolbar icon, but nothing happens when I click on it.

![image](https://cloud.githubusercontent.com/assets/33569/25876643/748162ac-34d3-11e7-9569-8ce6ce6a12f7.png)

**Comment by borisf** [comment]
Dan thanks, will look at, here are the best way to exporting data with ClassyShark (from ClassyShark tool set :))

https://medium.com/@BorisFarber/exporting-data-from-classyshark-e3cf3fe3fab8

**Comment by petruisfan** [comment]
You can use the cli for that:
`java -jar ClassyShark.jar -export file.apk AndroidManifest.xml`

**Comment by borisf** [comment]
Thanks all, closing
