### ISSUE TITLE
ClassyShark doesn't match APK Analyzer in Android Studio

### ISSUE THREAD

**Issue by IgorGanapolsky** [google/android-classyshark#157]
Hello,
I have added `org.altbeacon:android-beacon-library` gradle dependency. 
 I have multidex turned on in my project.  APK Analyzer in Android Studio shows **org.altbeacon.beacon.powersave** gradle in classes.dex.  However, ClassyShark doesn't show the same in the classes folder. 

Do you know what could be causing this?

Thank you,
Igor

**Comment by borisf** [comment]
Can you share the APK (via Google drive), and I take a look

**Comment by IgorGanapolsky** [comment]
@borisf I sent you the link to GDrive file.

**Comment by IgorGanapolsky** [comment]
Since the class `org.altbeacon.beacon.powersave.BackGroundPowerSaver` is not showing in classes.dex in ClassyShark, I get a **NoClassDefFoundError** at runtime.  However, at compiletime, it works in my project fine.

**Comment by IgorGanapolsky** [comment]
I figured out the problem.  Since I am using Adobe Air framework to package my final APK, I must include jars manually in the libs folder (instead of just relying on gradle).  Since I didn't include altbeacon jar, it wasn't packaged as part of my final APK, and wasn't in **classes.dex**.

APK Analyzer shows these problematic packages as italicized.
