### ISSUE TITLE
Can't find Synthetic Accessors information in ClassyShark 8.0

### ISSUE THREAD

**Issue by AndrazP** [google/android-classyshark#158]
![screen shot 2017-08-08 at 10 17 46](https://user-images.githubusercontent.com/1963904/29062698-f2b173c4-7c22-11e7-8882-af612274c6d5.png)
Same apk. Mouse focus on apk name. On the left v7.2, on the right 8.0.
Was Synthetic Accessors information removed or moved to other section?

**Comment by borisf** [comment]
We removed Synthethic Accessors from the APK dashboard as they were time consuming to calc, and not many users needed this feature. There are few solutions:

1. Un comment the following line (https://github.com/google/android-classyshark/blob/master/ClassySharkWS/src/com/google/classyshark/silverghost/translator/apk/dashboard/ApkDashboard.java#L127) and build your own ClassyShark version

2. If needed I can extract Synthetic accessors to be ClassyShark standalone API

**Comment by AndrazP** [comment]
Thank you for clarification.
