### ISSUE TITLE
Is it working on mac?

### ISSUE THREAD

**Issue by musso** [google/android-classyshark#159]
Seem that most of the ui functions are not working in mac, like
- changing the theme color
- export file
- expand method  (all the text inside the method now become dot dot dot, not sure if it is the problem of using mac or not. Below is the sample display)

```
import android.content.Context;
import java.lang.String;
import org.apache.http.Header;
import org.apache.http.client.CookieStore;

public class HttpCookies extends Object
{
    //======================== F I E L D S ==================


      public static String baseurl;
      private static Header[] httpHeader;
      private static String httpProxyStr;
      private static int pageSize;
      private static CookieStore uCookie;
       Context context;

    //======================== C O N S T R U C T O R S ======

    public HttpCookies(Context) { ... }

    //======================== M E T H O D S ================

    static void <clinit>() { ... }
    public Header[] getHttpHeader() { ... }
    public String getHttpProxyStr() { ... }
    public int getPageSize() { ... }
    public CookieStore getuCookie() { ... }
    public void initHTTPProxy() { ... }
    public void setPageSize(int) { ... }
    public void setuCookie(CookieStore) { ... }

} 
```

**Comment by musso** [comment]
I found out that the theme setting did apply after relaunch

**Comment by borisf** [comment]
Thanks, actually this is working as expected , let me elaborate more

* changing the theme color - yes, requires restart
* export file - just checked now, works
* expand method (all the text inside the method now become dot dot dot, not sure if it is the problem of using mac or not. Below is the sample display) - ClassyShark is not a decompiler, thus shows the class data without method internals
