### ISSUE TITLE
Java 8

### ISSUE THREAD

**Issue by anantshri** [google/android-classyshark#163]
Hi Team,

The latest build seems to be only working on java 8. is it intentional or by mistake.

Can i assume going forward all builds will be on java 8 only.

BTW just so you are aware. We package and make available classyshark in AndroidTamer as well as  on androidtamer debian compatible repository "https://repo.androidtamer.com/"

**Comment by borisf** [comment]
Yes, we are gradually moving to Java 8,  if this is a problem I can build and upload Java 7 compat

**Comment by anantshri** [comment]
Thanks for the confirmation. Should not be a problem. Debian has java 7 default so just need to tweak my launcher scripts to ensure we are launching this via java 8. Thanks for the headsup i will update the script and will push this out for everyone.

as always thanks for the wonderful work.

**Comment by borisf** [comment]
Sure, you can happily change the source config here (https://github.com/google/android-classyshark/blob/master/ClassySharkWS/build.gradle) to 1.7 and rebuild (by calling "gradle fatJar" from the command line)
