### ISSUE TITLE
Methodcount from classyshark is different from [dex-method-count](https://github.com/mihaip/dex-method-counts)

### ISSUE THREAD

**Issue by simpleton** [google/android-classyshark#164]
[Dex-method-count](https://github.com/mihaip/dex-method-counts) will count all methods include defined methods and referenced methods. Note that referenced methods count against the 64K method limit too.

Will Classyshark count the referenced method?

**Comment by borisf** [comment]
In the package-pie view ClassyShark counts and shows only the defined methods (recursively with in the package). If you click on the classesXXX.dex from the main APK view tree entry you see the total dex count of both referenced and defined methods.

CC @andreban

**Comment by simpleton** [comment]
Cool! Thx @borisf for quick feedback.
