### ISSUE TITLE
Opening a file, it shows wrong content 

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/android-classyshark#177]
For example, I choose some drawable file, and I see manifest content:

![image](https://user-images.githubusercontent.com/5357526/69764040-b09bc380-1177-11ea-9f58-d7085c7d68a1.png)

It shows at the top as if I chose a manifest file, but I didn't.

**Comment by borisf** [comment]
This is by design, for un supported files we show the manifest

**Comment by AndroidDeveloperLB** [comment]
This is highly unintuitive. Why the manifest? Why not show "We can't parse this file" instead?

**Comment by AndroidDeveloperLB** [comment]
Also, it's incorrect that you show the manifest all the time.
Look at this video. I searched and chose a drawable XML file, and got a weird content instead:

[2019-11-28_21-31-01.zip](https://github.com/google/android-classyshark/files/3902892/2019-11-28_21-31-01.zip)

How could a library that parses APK files by Google not work properly like on Android?
