### ISSUE TITLE
Request: offer as a library for Android, including de-obfuscation

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/android-classyshark#194]
Currently this repository became very old, and we can use most of it on Android Studio anyway.

Please update it, and offer to to get de-obfuscation of APK files, including ability to run it even on Android itself.

**Comment by borisf** [comment]
Thanks for the request

1. If Android Studio addresses your needs, we are more than happy
2. Deobfuscation - you can use Android Studio ([more details](https://developer.android.com/studio/build/apk-analyzer#load_proguard_mappings))
3. Ability to run on Android - this is out of our scope as a desktop tool

**Comment by AndroidDeveloperLB** [comment]
@borisf Is there anything this tool offers that isn't available on Android Studio?
Even online, I can get more, no?
Why can't it offer de-obfuscation? 
If the tool is so outdated, please consider making it better, and supporting Android too, or at least make it a bit easier.

**Comment by borisf** [comment]
At the moment, we don't have any plans to update ClassyShark, but we are open to pull requests :)

**Comment by AndroidDeveloperLB** [comment]
@borisf Does Google have any good alternative library to parse APK files (showing classes, resources, code...), which can run on Android?

**Comment by borisf** [comment]
I am not familiar

**Comment by AndroidDeveloperLB** [comment]
@borisf So Google made Android itself, including the APK standard, and both are open sourced, but there is no nice official library to parse them ...
:(
