### ISSUE TITLE
Add command line support without loading the UI at all

### ISSUE THREAD

**Issue by borisf** [google/android-classyshark#27]
Run ClassyShark from CLI 
java -jar ClassyShark.jar -export something.jar

**Comment by ithinkihaveacat** [comment]
As discussed, a small survey of what related tools use for this option:
- [jadx](https://github.com/skylot/jadx) uses `-d` or `--output-dir`.
- [apktool](http://ibotpeaches.github.io/Apktool/) uses `d` or `decode`.

**Comment by ithinkihaveacat** [comment]
Also:
- [CFR](http://www.benf.org/other/cfr/) uses `--outputdir`.

**Comment by borisf** [comment]
fixed in latest 4.0 release
