### ISSUE TITLE
can not see method content

### ISSUE THREAD

**Issue by bynop** [google/android-classyshark#41]
this tool is awesome`~but the weakness is  it can see nothing content of method in every class~~so if it will support in future?

**Comment by borisf** [comment]
Actually ClassyShark is designed and optimised for a quick browsing inside your Android/Java executable. To find a reason for run time misbehaviors the most granular unit I used is a method (especially synthetic ones https://docs.oracle.com/javase/tutorial/java/generics/bridgeMethods.html).

Now to look at method internals, you have the IDE which is build for that (+ code editing). So ClassyShark fills the niche that IDEs don't provide (actually they are not built for this).

If in your scenario you do need to see the actual method internals, let me know, and we see what can we do

**Comment by bynop** [comment]
thanks for your reply, i used to thought it's a decompile tool~~~
