### ISSUE TITLE
How to run on the windows

### ISSUE THREAD

**Issue by niknowzcd** [google/android-classyshark#57]
How to run on the windows，

**Comment by xxmbaobao** [comment]
first download classyshark.jar   open cmd  window use commandline like this:
java -jar <ClassyShark.jar path> -open  <your apk path>

**Comment by borisf** [comment]
get the latest jar from releases ==> https://github.com/google/android-classyshark/releases

run the jar on Windows according to this ==> http://stackoverflow.com/questions/394616/running-jar-file-on-windows

Please let us know if there is a problem
