### ISSUE TITLE
Extract own app package from manifest and use it for data in methods pie chart, for showing own methods

### ISSUE THREAD

**Issue by borisf** [google/android-classyshark#64]
Thanks https://github.com/tmelz

**Comment by tmelz** [comment]
Consider displaying a warning if the % of total methods is less than some threshold! I think <=30% would would be a very likely indication that something is wrong.

**Comment by andreban** [comment]
Trying to understand the broader idea. Is it to mark in the interface which packages are 1st party and which ones are 3rd parties?

A small nit is that the package declared in the APK doesn't have to match the actual packages used in the code. Most applications will follow the convention tough.

**Comment by borisf** [comment]
Moved to ClassyShark roadmap
