### ISSUE TITLE
OS X: search results disappear if command (⌘) is pressed

### ISSUE THREAD

**Issue by ithinkihaveacat** [google/android-classyshark#8]
The search results disappear if the command key is pressed. To reproduce:
1. Open an APK.
2. Type `Manifest` such that at least one file is matched.
3. Hit the command (⌘) key.

Actual: the search results disappear.

Expected: the search results still appear. (Minor bug, but it makes it difficult to take screenshots of the search results screen.)

**Comment by ithinkihaveacat** [comment]
Actually, how did you get the screenshot for https://plus.google.com/+AndroidDevelopers/posts/ayMj2FddVrz? That's what I was trying to do, maybe I'm doing something wrong…

**Comment by borisf** [comment]
fixed, here is the commit https://github.com/google/android-classyshark/commit/7a7dfa3ab7d26ae8fe94c51b65d29b18aa41f15a
